### ISSUE TITLE
do you even flute bro

### ISSUE THREAD

**Issue by Mygod** [jswxdzc/Sibrary#1]
just curious

**Comment by Incises** [comment]
Amateur. With little time for practice.

**Comment by Incises** [comment]
![do_i](https://user-images.githubusercontent.com/7011556/36308379-6b94d93c-135b-11e8-9de4-a6282a41c878.jpg)
Not a single chance to practice at school before Gaokao next year.
Luckily I can study the orchestration all year round thanks to the miniature study scores.

**Comment by Mygod** [comment]
I'd suggest you to read more scores in your spare time.

**Comment by Incises** [comment]
Yes. I read quite a few scores of some romantic and modernist composers last year. 
I was deeply influenced by the notations of the scores. 
And is a solid study of Bach required before Bartók, isn't it?

**Comment by Incises** [comment]
You are more familiar with the French composers, aren't you?

**Comment by Mygod** [comment]
I guess. Your writing for flute has very few slurs. This gives it a very baroque/classical keyboard-style feeling which I don't think fits the mood of the piece.

**Comment by Incises** [comment]
OMG I forgot to add them in the songs as they make no difference in the Sibelius program. 
I actually play slurs when trying those sentences.
